global:
  scrape_interval: 30s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx] # Change this to the module you want to use
    static_configs:
      - targets:
        - https://mainnet.zus.network
        - https://0box.mainnet.zus.network
        - http://kamrul.store/
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115  # The Blackbox exporter's address
